apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qonob0syp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qonob0syp-nodejs 
  name: qonob0syp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qonob0syp-nodejs 
